import { ref, computed, reactive } from 'vue'
import { defineStore } from 'pinia'

export const useMori = defineStore('mori', () => {
	const a=ref(0);
	const words_welcome=reactive({
			"school":"مدرسه",
			"classroom":"کلاس درس",
			"door":"درب",
			"blackboard":"تخته سیاه",
			"desk":"میز",
			"chair":"صندلی",
			"pen":"خودکار",
			"pencil":"مداد",
			"book":"کتاب",
			"notebook":"دفترچه",
			"ruler":"خط کش",
			"dictionary":"لغت نامه",
			"bag":"کیف",
			"eraser":"پاک کن",
			"pencil sharpener":"مداد تراش",
			"backpack":"کوله پشتی",
			"marker":"ماژیک",
			"bench":"نیمکت",
			"pencil case":"جا مدادی",
			"chalk":"گچ",
		});   
	const words_71=reactive({
			"sit down":"بنشین-بنشینید",
			"stand up":"بلند شو- شوید",
			"boy":"پسر",
			"girl":"دختر",
			"man":"مرد",
			"woman":"زن",
			"teacher":"معلم",
			"student":"دانش آموز",
			"library":"کتابخانه",
			"library card":"کارت عضویت کتابخانه",
			// "ــــــــــــــــــــ":"ــــــــــــــــــــ",
			// "ــــــــــــــadded from contextــــ":"ــــــــــــــــــــ",
			"lesson":"درس",
			"first name":"نام کوچک",
			"last name":"نام خانوادگی",
			"Good morning":"صبح بخیر",
			"Good afternoon":"عصر بخیر",
			"English":"زبان انگلیسی",
			"Persian":"زبان فارسی",
			"conversation":"مکالمه",
			"greeting":"سلام و احوال پرسی",
			"name":"نام",
			"now":"نام",
			"group":"گروه",
			"table":"میز",
			"best":"بهترین",
			"item":"عالی-زیاد-بزرگ",
		}); 
	const context_7=reactive({
			// "Teacher\: Hi, class\!":"معلم سلام (بچه های ) کلاس",
			"teacher":"معلم",
			"hi":"سلام",
			"class":"کلاس",
			"class!":"کلاس",
			"student":"دانش آموز",
			"students":"دانش آموزان",
			"hello":"سلام",
			"thank":"",
			"you":"a",
			"thank you\,":"مرسی-تشکر می کنم از شما",
			"thank you\.":"مرسی-تشکر می کنم از شما",
			"sit":"نشستن",
			"down":"پایین",
			"sit down":"بنشین",
			"sit down\,":"بنشین",
			"sit down\, please\.":"لطفا بنشین-لصفا بنشینید",
			"please":"لطفا",
			"i":"من",
			"i\'m":"من هستم",
			"your":"ات-تان",
			"english":"انگلیسی",
			"english teacher":"معلم انگلیسی",
			"your english teacher":"معلم انگلیسی تان",
			"my":"ام",
			"name":"نام-اسم",
			"names":"نام ها",
			"my name":"اسم ام-اسم من",
			"is":"هست",
			"ahmad":"احمد",
			"karimi":"کریمی",
			"now":"حالا",
			"now\'":"حالا",
			"tell":"بگو- بگویید",
			"me":"به من- مرا",
			"tell me":"به من بگویید\/بگو",
			"your names":"اسم های تان",
			"your names\.":"اسم های تان",
			"what":"چی",
			"what\‍'s":"چی هست-مخفف(what is)",
			"your name":"اسمت- اسم ات",
			"your name\?":"اسمت- است تو",
			"student 1":"دانش آموز اول",
			"student 2":"دانش آموز دوم",
			"my name is":"اسم من هست",
			"ali":"علی",
			"mohammadi":"محمدی",
			"how":"چطور",
			"how are":"چطوری-چطور هستی-چطور هستید",
			"how are you\,":"چطور هستی تو- چطوری",
			"fine":"خوب",
			"and":"و",
			"-------------":"-------------",

			"who":"کی",
			"who is":"کیه- کی هست",
			"that":"آن",
			"boy":"پسر",
			"that boy":"آن پسر-اون پسره",
			"parham":"پرهام",
			"that\'s":"اون هست- آن هست",
			"erfan":"عرفان",
			"he":"او",
			"he\'s":"او هست",
			"our":"مان",
			"new":"جدید",
			"class":"کلاس",
			"new classmate\.":"همکلاسی جدید",
			"our new classmate":"همکلاسی جدید مان",
			"let":"اجازه دادن",
			"let\'s":"بیا",
			"talk":"صحبت کنیم",
			"to":"با- به",
			"him":"او-او را-با او- به او",
			"let\'s talk to him":"بیا با او سحبت کنیم",
			"this":"این",
			"nice":"خوب",
			"meet":"مقالات کردن",
			"nice to meet you":"از ملاقات با شما خوشبختم",
			"nice to meet you\,":"از ملاقات با شما خوشبختم",
			"too":"همچنین",
			"welcome":"خوش آمدی-خوش آمدید",
			"welcome to":"خوش آمدی به",
			"our school":"مدرسه ما- مدرسه مان",
			"-------------":"-------------",
			"nargess":"نرگس",
			"when":"کی-چه زمانی",
			"when is":"کی هست- چه زمانی هست",
			"birthday":"تولد",
			"your birthday":"تولد تو-تولد تان",
			"your":"تان",
			"it\'s":"ان هست",
			"mehr":"مهر-ماه مهر",
			"thank":"تشکر کردن",
			"in mehr":"در مهر-در ماه مهر",
			"really":"واقعا",
			"how old ":"چند ساله",
			"how old are":"چند ساله هستی",
			"how old are you":"چند ساله هستی تو - من ۱۲ سالمه",
			"you":"تو-شما",
			"i\'m":"من هستم",
			"i\'m 12":"من هستم ۱۲(من ۱۲ سالم هست(",
			"what about you":"تو چطور",
			"tahereh":"طاهره",
			"my birthday":"تولد من",
			"my birthday is in":"تولد من هست در ",
			"in":"در",
"-------4------":"------4-------",
			"picture":"تصویر",
			"your father":"پدر تو-پدرت",
			"yes":"بله",
			"how old":"چند ساله",
			"how old is he":"چند ساله هست او- چند سالشه",
			"job":"شغل",
			"his":"اش- مثل شال اش",
			"his job":"شغل اش",
			"he\'s":"او هست",
			"a":"یه-یک",
			"mechanic":"مکانیک",
			"a mechanic":"یه مکانیک-یک مکانیک",
			"your mother":"مادر تو-مادرت",
			"she\'s":"او هست",
			"she\'s 35":"او ۳۵ ساله هست",
			"she":"او\/مونث",
			"housewife":"خانه دار",
"------5-------":"------5-------",
			"father":"پدر",
			"no":"نه",
			"my english teacher":"معلم انگلیسی من-معلم انگلیسی ام",
			"the":"حرف تعریف",
			"tall":"بلند قد",
			"man":"مرد",
			"tall man":"مرد بلند قد",
			"wearing":"پوشیده-پوشیده است",
			"gray":"خاکستری",
			"gray suit":"کت و شلوار خاکستری",
			"suit":"کت و شلوار",
			"over":"آن سوی",
			"there":"آنجا",
			"over there":"آنطرف",
			"which":"کدام",
			"which one":"کدام یکی- کدوم یکی",
			"math":"ریاضی",
			"math teacher":"معلم ریاضی",
			"your math teacher":"معلم ریاضی ات",
			"which one is":"کدوم یکی هست",
			"blue":"آبی",
			"blue suit":"کت و شلوار آبی",
			"shirt":"پیراهن",
			"white":"سفید",
			"white shirt":"پیراهن سفید",
			"first":"در ابتدا- اول- اولین",
"-------6------":"-------6------",
			"farid":"فرید",
			"mom":"مادر",
			"where":"کجا",
			"where are":"کجا هستی",
			"where are you":"کجا هستی تو",
			"where\'s dad":"کجا هست پدر",
			"kitchen":"آشپزخانه",
			"where\'s":"کجایی- کجا هستی",
			"garage":"کاراژ",
			"so":"خیلی-بنابراین",
			"hungry":"گرسنه",
			"so hungry":"خیلی گرسنه",
			"wash":"شستن-بشور",
			"hands":"دست ها",
			"come":"بیا",
			"for":"برای",
			"lunch":"نهار",
			"for lunch":"برای نهار",
			"i\'ll":"من خواهم-فعل کمکی آینده",
			"call":"تماس بگیر-زنگ زدن",
			"dad":"پدر",
			"fixing":"تعمیر کردن-تعمیر می کند",
			"car":"ماشین",
"--------7-----":"------7-------",
			"omid":"امید",
			"ali\'s":"علی هست",
			"not":"(فعل کمکی برای منفی کردن)",
			"not well":"خوب نیست",
			"ali\'s not well":"علی خوب نیست-حالش خوب نیست",
			"i\'m going to":"من قصد دارم",
			"him":"او را",
			"today":"امروز",
			"are you coming":"میایی-آیا تو میایی",
			"with":"با",
			"with me":"با من",
			"hossein":"حسین",
			"what time":"چه زمانی",
			"going":"(حالت استمراری-رفتن)",
			"what time are you going":"کی می خواهی بری",
			"around":"نزدیک",
			"around 5":"نزدیک ساعت ۵-نزدیک ۵",
			"in the afternoon":"بعد از ظهر- در بعد از ظهر",
			"i\'m not sure":"من مطمعن نیستم",
			"can":"توانستن",
			"i can":"من می توانم",
			"i\'m not sure i can":"من مطمعن نیستم که بتونم",
			"but":"اما",
			"sure":"مطمعن بودن- اطمینان دادن",
			"but i\'ll try":"ولی سعی خودم رو می کنم",
			"try":"سعی می کنم-سعی کردن",
			"address":"ادرس-نشانی",
			"his address":"ادرس او- نشانی اش",
			"what\'s his address":"ادرش اش چی هست",
			"azadi":"آزادی",
			"street":"خیابان",
			"call":"تماس بگیر- زنگ بزن",
			"call me":"با من تماس بگیر",
			"before":"قبل از",
			"before you go":"قبل از اینکه بری",
			"phone":"تلفن",
			"number":"شماره-عدد",
			"phone number":"شماره تلفن",
			"my phone number":"شماره تلفن من",
			"my phone number is":"شماره تلفن من هست",
			"bye":"خداحافظ",

"--------8-----":"------8-------",
			"look":"نگاه کن-ببین",
			"enough":"کافی- باندازه کافی",
			"hungry":"گرسنه",
			"how":"چطور",
			"how about you":"تو چطور",
			"about":"درباره",
			"me\, too":"منم همینطور",
			"have":"مصدر\:داشتن-خوردن",
			"some":"بعضی-مقداری",
			"cake":"کیک",
			"milk":"شیر",
			"cake and milk":"کیک و شیر",
			"let\'s have some cake and milk":"بیا مقداری کیک و شیر بخوریم",
			"sounds":"بنظر ... می رسد",
			"good":"خوب",
			"Sounds good":"بنظر خوب میاد-بنظر خوب می رسد",
			"i\'d":"من میل دارم-مایلم-می خواهم",
			"i\'d like":"من میل دارم",
			"like":"مثل-شبیه",
			"tea":"چای",
			"with":"با",
"--------8-1-----":"------8-1-------",
			"shayan":"شایان",
			"mr":"آقای-آقا",
			"mr\.":"آقای - آقا",
			"chaychi":"چایچی",
			"cousin":"پسرعمو\/پسرعمل",
			"my cousin":"پسرعمو\/پسرعمل من",
			"sam":"سم",
			"speaks":"صحبت می کند",
			"speak":"صحبت کردن",
			"french":"فرانسوی-زبان فرانسوی",
			"english":"انگلیسی",
			"little":"کمی-کوچک",
			"a little":"یه کمی- مقدار کمی",
			"persian":"فارسی-زبان فارسی",
			"a little persian":"یه کمی فارسی- یه مقداری فارسی",
			"oh":"اوو",
			"nice to meet you":"از مقالات شما خوشبختم",
			"from":"از",
			"i\'":"من",
			"\'m":"هستم",
			"iran":"ایران",
			"from iran":"اهل ایران-از ایران",
			"are you from iran":"شما اهل ایران هستید\؟",
			"originally":"اصالتا",
			"iranian":"ایرانی",
			"live":"زندگی می کند",
			"france":"فرانسه",
			"our class":"کلاس مان- کلاس ما",
			"do":"فعل کمکی زمان حال ساده",
			"great":"عالی",
			"love":"دوست دارم-دوست داشتن",
			"beautiful":"زیبا",
			"country":"کشور",
"--------8-2-----":"------8-2-------",
			"do":"انجام دادن-فعل کمکی زمان حال ساده",
			"afternoon":"بعد از ظهر",
			"reihaneh":"ریحانه",
			"go":"رفتن-می روم -می روی - برو",
			"gym":"باشگاه",
			"sundays":"یکشنبه ها",
			"tuesdays":"سه شنبه",
			"friday":"جمعه",
			"friday mornings":"جمعه صبح",
			"morning":"صبح",
			"stay":"ماندن- اقامت کردن",
			"at":"در",
			"at home":"در خانه",
			"home":"خانه",
			"relax":"استراحت کردن",
			"why":"چرا",
			"know":"دانستن",
			"you know":"می دونی",
			"is not":"نیست",
			"very":"خیلی",
			"very good":"خیلی خوب",
			"at english":"در انگلیسی",
			"can you":"می تونی",
			"help":"کمک کنی- کمک کردن...",
			"her":"به او- او را",
			"oh":"او",
			"sure":"حتما- مطمپن بودن",
			"that sounds great":"علی بنظر میرسه",
			"start":"شروع کردن-شروع",
			"wednesday":"پنج شنبه",
			"let":"اجازه دادن",
"--------8-۳-----":"------8-۳-------",
			"elham":"الهام",
			"wow":"واوو",
			"drawing":"نقاشی",
			"very good":"خیلی خوب",
			"thanks":"ممنون-مرسی",
			"can you draw":"می توانی نقاشی بکشی",
			"draw":"نقاشی کشیدن-نقاشی می کشم ...",
			"can":"توانستن-می توانی- می توانم",
			"let":"اجازه دادن-اجازه می دهم-اجازه میدهی..اجازه بده",
			"take":"گرفتن",
			"take good photos":"عکس های خوب گرفتن",
			"photo":"عکس",
			"photos":"عکس ها",
			"take photo":"عکس گرفتن",
			"really":"واقعا",
			"see":"دیدن",
			"your photos":"عکس هایت",
			"why not":"چرا که نه",
			"come":"آمدن- بیا",
			"house":"خانه",
			"my house":"خانه ام- خانه من",
			"come to my house":"به خانه من بیا",
			"make":"ساختن",
			"favorite":"مورد علاقه-پسند",
			"how about":"چظوره ....",
			"how about Thursday":"سه شنبه چطوره",
			"how about Thursday afternoon":"سه شنبه بعد از ظهر چطوره",
			"that\'s fine":"خوبه",
			"bring":"آوردن",
			"drawing book":"دفتر نقاشی",
"--------8-۴-----":"------8-۴-------",
			"ok":"بسیار خب-علامت تایید-خوب",
			"are you ok":"تو خوبی-خوبی\!",
			"i\'m not":"من ... نیستم",
			"headache":"سر درد",
			"i have a headache":"سر درد دارم",
			"sore":"سرخی",
			"eye":"چشم",
			"eyes":"چشم ها",
			"sore eyes":"سوزش چشم",
			"should":"باید",
			"rest":"استراحت-استراحت کردن",
			"one":"یک",
			"don\'t":"فعل کمکی منفی حال ساده",
			"don\'t worry":"نگران نباش",
			"for":"برای",
			"help":"کمک-کمک کردن",
			"office":"اداره",
			"parents":"والدین",
			"be":"باش-بودن",
			"quiet":"آرام",
			"be quiet":"آرام باش",
			"back":"عقب",
			"in a minute":"در عرض یه دقیقه",
			"minute":"دقیقه",
"--------8-5-----":"------8-5-------",
			"phanindra":"فانیندرا",
			"morteza":"مرتضی",
			"tell":"گفتن-بگو-می گویم ..",
			"tell me":"به من بگو",
			"about":"درباره ",
			"isfahan":"اصفحان",
			"well":"خوب- خب",
			"isfahan\'s":"اصفحان هست",
			"an":"یک",
			"old":"سن- سال- پیر- کهنه",
			"city":"شهر",
			"center":"مرکز",
			"like":"دوست داشتن-شبیه بودن",
			"big":"بزرگ",
			"clean":"تمیز",
			"any":"هر یک- هیچ یک",
			"famous":"مشهور",
			"buildings":"ساختمان ها",
			"building":"ساختمان",
			"many":"تعداد زیادی",
			"actually":"واقعا",
			"mosques":"مسجد ها",
			"mosque":"مسجد ",
			"palaces":"قصرها",
			"palace":"قصر",
			"museums":"موزه ها",
			"museum":"موزه",
			"soon":"بزودی",
			"special":"مخصوص",
			"food":"غذا",
			"downtown":"پایین شهر",

"--------8-6-----":"------8-6-------",
			"hamid":"حمید",
			"ghez-ghal\'eh":"...",
			"village":"روستا",
			"west":"غرب",
			"azarbaijan":"آذربایجان",
			"near":"نزدیک",
			"khoy":"خوی",
			"mountain":"کوه-کوهستان",
			"mountain village":"روستای کوهستانی",
			"tree":"درخت",
			"trees":"درخت-درختان",
			"flowers":"گل ها",
			"flower":"گل",
			"sunflower":"گل آفتاب گردان",
			"its":"صفت مالکیت",
			"fields":"مزارع",
			"people":"مدرم",
			"they":"آنها",
			"work":"کار می کنند-کار کردن",
			"farm":"مزرعه",
			"farms":"مزرعه ها",
			"raise":"پرورش می دهند-پرورش دادن ",
			"animals":"حیوانات",
			"animal":"حیوان",
			"weather":"هوا-آب و هوا",
			"there":"آنجا",
			"there\'s":"آنجا هست",
			"a lot of":"تعداد زیادی",
			"lot":"زیاد",
			"wind":"باد",
			"summer":"تابستان",
			"fall":"پاییز",
			"winter":"زمستان",
			"cold":"سرد",
			"aban":"آبان-آبان ماه",
			"farvardin":"فروردین",
			"interesting":"جالب",
			"place":"مکان-جا-جای",
"--------8-7-----":"------8-7-------",
			"hobby":"سرگرمی",
			"hobbies":"سرگرمی ها",
			"zahra":"زهرا",
			"watch":"تماشا کردن",
			"movies":"فیلم های سینمایی",
			"movie":"فیلم سینمایی",
			"as":"مثل-بعنوان-همانطور که",
			"how about you":"تو چطور",
			"samira":"سمیرا",
			"read":"خواندن-مطالعه کردن",
			"reading":"مطالعه-خواندن",
			"sort":"نوع-جور-قسم",
			"what sort":"چه جور- چه نوعی",
			"things":"چیزها",
			"thing":"چیز",
			"books":"کتاب ها",
			"magazine":"مجله",
			"magazines":"مجلات",
			"sports":" ورزشی",
			"sports news":"اخبار ورزشی",
			"news":"اخبار",
			"net":"اینترنت",
			"on":"در- در روی",
			"sometimes":"گاهی اوقات",
			"poems":"اشع ها- اشعار",
			"poem":"شعر",
			"mrs":"خانم",
			"emami":"امامی",
			"free":"آزاد",
			"free time":"وقت آزاد",
"--------9-1-----":"------9-1-------",
			"ehsan":"احسان",
			"best":"بهترین",
			"friend":"دوست",
			"school":"مدرسه",
			"parham":"پرهام",
			"reza":"رضا",
			"what\'s he like":"چه جور آدمی هست",
			"clever":"باهوش",
			"kind":"مهربان",
			"hard-working":"پرتلاش-سخ تکوش",
			"hard":"سخت",
			"always":"همیشه",
			"helpful":"مفید",
			"helps":"کمک می کند",
			"lessons":"درس ها",
			"lesson":"درس",
			"my lessons":"درسهایم-درس های من",
"--------9-2-----":"------9-2------------------",
			"receptionist":"متصدی پذیرش",
			"hotel":"هتل",
			"sir":"آقا",
			"how can i help you":"چطور می تونم کمک تون کنم",
			"tourist":"گردشگر",
			"paul":"پاول",
			"kress":"کرس",
			"germany":"آلمان",
			"i\'m from germany":"من اهل آلمان هستم",
			"reservation":"رزرو-رزرو اتاق",
			"see":"دیدن-می بینم-می دانم",
			"staying":"اقامت",
			"here":"اینجا",
			"night":"شب",
			"nights":"شب ها",
			"two nights":"۲ شب",
			"wife":"همسر-زن",
			"visiting":"ملاقات",
			"tehran":"تهران",
			"three":"سه -۳",
			"day":"روز",
			"days":"روزها",
			"three days":"۳ روز",
			"need":"نیاز داشتن-نیاز دارم ..",
			"check":"چک کردن-بازبینی کردن",
			"passport":"گذرنامه",
			"standing":"ایستاده-",
			"by":"نزدیک-بوسیله",
			"by the":"نزدیک",
			"by gift":"...",
			"shop":"مغازه",
			"key":"کلید",
			"room":"اتاق",
			"hope":"امیدوارم-امید-امیدوار بودن",
			"enjoy":"لذت ببرید-لذت بردن",
"--------9-3-----":"------9-3------------------",

			"just":"فقط",
			"new":"جدید",
			"year":"سال",
			"holidays":"تعطیلات",
			"normally":"معمولا",
			"relatives":"بستگان-آشنایان",
			"nnorooz":"عید نوروز",
			"fun":"جالب",
			"nasrin":"نسرین",
			"get":"گرفتن",
			"gifts":"هدایا",
			"gift":"هدیه",
			"money":"پول",
			"grandmother\` houses":"خانه مادربزرگ",
			"grandmother\`":"مادر بزرگ",
			"does":"فعل کمکی سوم شخص زمان حال ساده-انجام می دهد",
			"grandmother":"مادربزرگ",
			"your grandmother":"مادربزرگ ات",
			"cook":"پختن- میپزد",
			"meal":"وعده غذایی",
			"actually":"راستش-در واقع",
			"mother":"مادر",
			"makes":"درست می کند",
"--------9-4-----":"------9-4------------------",
			"excuse":"عذر خواستن",
			"excuse me":"معذرت می خوام-ببخشید",
			"excuse me sir":"ببخشید جناب-ببخشید آقا",
			"can you help me":"می تونید به من کمک کنید",
			"pedram":"پدرام",
			"what can i do for you":"چکار می تونم برای شما انجام دهم",
			"want":"می خواهم- خواستن",
			"postcard":"...",
			"envelope":"",
			"stamp":"",
			"umm":"عمم",
			"them":"آنها را- به آنها",
			"post":"پست",
			"post office":"اداره پست",
			"open":"باز-باز شدن-باز کدن",
			"opens":"باز می شود",
			"office":"اداره",
			"round":"...",
			"corner":"گوشه",
			"round the corner":"",
			"what time":"کی-چه زمانی",
			"what time does it open":"کی باز می کنه",
			"thanks a lot":"خیلی ممنون-تشکر بسیار",
"--------9-5-----":"------9-5------------------",
			"mina":"مینا",
			"did":"فعل کمکی گذشه ساده-انجام دادن",
			"weekend":"آخر هفته",
			"mahsa":"مهسا",
			"wonderful":"شگفت انگیز",
			"attended":"شرکت کردم",
			"attend":"شرکت کردن",
			"fajr":"فجر",
			"International":"بین المللی",
			"film":"فیلم",
			"festival":"جشنواره",
			"also":"همچنین",
			"interested":"علاقه مند",
			"interested in":"علاقه مند به",
			"events":"رویدادهای",
			"reports":"گزارش ها",
			"tv":"تلوزیون",
			"last":"۱-گذشته۲-آخرین",
			"last night":"شب گذشته",
			"surf":"سرچ-جستجو کردن",
			"website":"وبسایت- تارنما",
			"if":"اگر",
			"if you like":"اگر دوست داری",
			"are":"هستی-هستید-هستند-هستیم",
			"there are":"آنجا هست",
			"Could":"توانستن- از افعال کمکی",
			"give":"داده-بدهی",
			"give me":"بدهی به من",
			"just a moment":"یه لحظه",
			"i just texted it":"همین الان پیامکش کردم",
"--------9-6-----":"------9-6------------------",
			"we":"ما",
			"plan":"نقشه",
			"lake":"دریاچه",
			"do you want":"تو می خواهی؟",
			"do you want to come":"می خوای بیای",
			"think":"فکر کردن",
			"i don\'t think so":"فکر نکنم",
			"trips":"اردو-گردش",
			"school trips":"اردوهای مدرسه",
			"last summer":"تابستان گذشته",
			"fell":"افتادن",
			"i fell":"من افتادم",
			"broke":"شکست",
			"leg":"پا",
			"my leg":"پایم-پای من",
			"happens":"اتفاق می افتد",
			"happen":"اتفاق افتادن",
			"twisted":"پیچید",
			"ankle":"مچ پا",
			"bad":"بد",
			"too bad":"خیلی بد",
			"yeah":"اره",
			"after":"بعد از",
			"after that":"بعد از آن",
			"participated":"مشارکت کردن",
			"participated in":"شمارکت کردن در",
			"helal-e-ahmar":"هلال احمر",
			"first aid":"کمک های اولیه",
			"classes":"کلاس ها",
			"learned":"یاد گرفتم",
			"take":"گرفتن-بردن",
			"take care":"مراقبت کردن",
			"take care of":"مراقبت کردن از",
			"myself":"خودم",
			"of myself":"از خودم",
			"advice":"پند-توصیه",
		});  





const words_72=reactive({
		"لغات درس یک و دو مشترک بود":"",
		
	}); 
const words_73=reactive({
		"saturday":"شنبه",
		"Thursday":"پنج شنبه",
		"sunday":"یکشنبه",
		"monday":"دوشنبه",
		"friday":"جمعه",
		"tuesday":"سه شنبه",
		"wednesday":"چارشنبه",
		"date":"تاریخ",
		"month":"ماه",
		"January":"ژانویه",
		"February":"فبریه",
		"March":"مارس",
		"April":"آوریل",
		"May":"می",
		"June":"جون",
		"July":"جولای",
		"August":"آگوست",
		"September":"سپتامبر",
		"October":"اکتبر",
		"November":"نوامبر",
		"one":"یک",
		"two":"دو",
		"three":"سه",
		"four":"چهار",
		"five":"پنچ",
		"six":"شش",
		"seven":"هفت",
		"eight":"هشت",
		"nine":"نه",
		"ten":"ده",
		"eleven":"یازده",
		"twelve":"دوازده",
		"thirteen":"سیزده",
		"fourteen":"چهارده",
		"fifteen":"پانزده",
		"sixteen":"شانزده",
		"seventeen":"هفده",
		"eighteen":"هجده",
		"nineteen":"نوزده",
		"twenty":"بیست",
		"thirty":"سی",
		"forty":"چهل",
		"fifty":"پنجاه",
		"sixty":"شصت",
		"seventy":"هفتاد",
		"eighty":"هشتاد",
		"ninety":"نود",
		"one hundred":"صد",
	}); 
const words_74=reactive({
		"engineer":"مهندس",
		"painter":"نقاش",
		"farmer":"کشاورز",
		"florist":"گل فروش",
		"policeman":"پلیس مرد",
		 "employee":"کارگر",
		"postman":"پستچی مرد",
		 "waiter":"خدمتکار- پیش خدمت",
		"teacher":"معلم",
		 "mechanic":"مکانیک",
		"doctor":"پذشک",
		 "shopkeeper":"مغازه دار",
		"dentist":"دندان پذشک",
		 "pilot":"خلبان",
		"nurse":"پرستار",
		 "baker":"نانوا",
		"driver":"راننده",
		 "worker":"کارگر",
		"cook":"آشپز",
	}); 

const words_75=reactive({
"appearance":" ظاهر",
"teacher":" معلم",
"tall":" قد بلند",
"man":" مرد",
"math":" ریاضی",
"woman":" زن",
"short":" کوتاه",
"old":" پیر",
"young":" جوان",
"gloves":" دستکش",
"blue":" آبی",
"red":" قرمز",
"yellow":" زرد",
"green":" سبز",
"brown":" قهوه‌ای",
"black":" سیاه",
"white":" سفید",
"gray":" خاکستری",
"orange":" نارنجی",
"pink":" صورتی",
"trousers(Pants)":" شلوار",
"jacket":" ژاکت",
"suit":" کت و شلوار",
"chador":" چادر",
"manteau":" مانتو",
"scarf":" روسری",
"sandals":" صندل",
"sunglasses":" عینک آفتابی",
"belt":" کمربند",
"socks":" جوراب",
"coat":" کت",
"glasses":" عینک",
"dress":" پیراهن زنانه",
"sweater":" ژاکت",
"cap":" کلاه لبه دار",
"T-shirt":" تی شرت",
"shoes":" کفش",
"shirt":" پیراهن",

	}); 
const words_76=reactive({
		
	}); 
const words_77=reactive({
		"school":"مدرسه",
	}); 
const words_78=reactive({
		"school":"مدرسه",
	}); 
// const dd = computed(() => dic.hi)

function go() {
		  	for (let i in dic){
		  		console.log(i); 
		  	}
}

function godef() {
		  	for (let i in dic){
		  		console.log(dic[i]); v
		  	}
}



  return {
    words_welcome,
    words_71,
    words_72,
    words_73,
    words_74,
    words_75,
    words_76,
    words_77,
    words_78,
	context_7	
	}
})
